name: Publish-Staging

on:
  push:
    branches: [ staging ]

jobs:

  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install boto3
        run: python -m pip install boto3        
      - name: Run upload script
        run: python upload_loot_distribution.py
        env:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_s3_bucket: ${{ secrets.AWS_STAGING_BUCKET }}
